package Visao;
import Dados.Usuario;
import Exceptions.FalhaNoCadastroException;
import Exceptions.FalhaNaBuscaException;
import Exceptions.FalhaNaRemocaoException;
import Exceptions.FalhaNaEdicaoException;
import Negocios.FachadaUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paulo
 */
public class TUsuario extends javax.swing.JFrame {

    static Usuario usuario;
        
    public TUsuario(Usuario usuario) {
        initComponents();
        this.usuario= usuario;
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarManga = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonConsultarColecao = new javax.swing.JButton();
        jButtonCadastrarColecao = new javax.swing.JButton();
        jLabelColecoes = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEditarUsuario = new javax.swing.JMenu();
        jMenuRemoverUsuario = new javax.swing.JMenu();
        jMenuDadosUsuario = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuario");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonCadastrarManga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastrarManga.setText("Cadastrar Mangá");
        jButtonCadastrarManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrarMangaMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonCadastrarManga);
        jButtonCadastrarManga.setBounds(210, 80, 140, 27);

        jButtonRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoverMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRemover);
        jButtonRemover.setBounds(210, 130, 140, 27);

        jButtonConsultarColecao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConsultarColecao.setText("Consultar Coleção");
        jButtonConsultarColecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarColecaoMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonConsultarColecao);
        jButtonConsultarColecao.setBounds(30, 130, 140, 27);

        jButtonCadastrarColecao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastrarColecao.setText("Cadastrar Coleção");
        jButtonCadastrarColecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrarColecaoMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonCadastrarColecao);
        jButtonCadastrarColecao.setBounds(30, 80, 140, 27);

        jLabelColecoes.setFont(new java.awt.Font("Freestyle Script", 1, 48)); // NOI18N
        jLabelColecoes.setText("Coleções:");
        getContentPane().add(jLabelColecoes);
        jLabelColecoes.setBounds(30, 20, 140, 40);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo1.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 600, 280);

        jMenuEditarUsuario.setText("Editar Usuario");
        jMenuEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditarUsuarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEditarUsuario);

        jMenuRemoverUsuario.setText("Remover Usuario");
        jMenuRemoverUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRemoverUsuarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRemoverUsuario);

        jMenuDadosUsuario.setText("Dados do Usuário");
        jMenuDadosUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDadosUsuarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDadosUsuario);

        jMenuLogout.setText("Logout");
        jMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(602, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEditarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditarUsuarioMouseClicked
        TEditarUsuario tela = null;
        try {
            tela = new TEditarUsuario(usuario);
        } catch (FalhaNaBuscaException ex) {
            Logger.getLogger(TUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuEditarUsuarioMouseClicked

    private void jMenuRemoverUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRemoverUsuarioMouseClicked
				int dialogButton = JOptionPane.YES_NO_OPTION;
				int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja excluir a conta?", "Excluindo conta",
						dialogButton);
				if (dialogResult == 0) {
					try {
						FachadaUsuario.getInstance().remover(usuario.getLogin());
						JOptionPane.showMessageDialog(null, "Removido com sucesso !");
						TelaLogin tela = new TelaLogin(); 
						tela.setVisible(true);
						dispose();
					} catch (FalhaNaRemocaoException e1) {
						e1.getMessage();
						e1.printStackTrace();
					}
				}
    }//GEN-LAST:event_jMenuRemoverUsuarioMouseClicked

    private void jMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogoutMouseClicked
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuLogoutMouseClicked

    private void jMenuDadosUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDadosUsuarioMouseClicked
        JOptionPane.showMessageDialog(null, usuario.toString());
    }//GEN-LAST:event_jMenuDadosUsuarioMouseClicked

    private void jButtonCadastrarColecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarColecaoMouseClicked
        TCadastroColecao tela = new TCadastroColecao(usuario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadastrarColecaoMouseClicked

    private void jButtonCadastrarMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarMangaMouseClicked
        TCadastroManga tela = new TCadastroManga(usuario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadastrarMangaMouseClicked

    private void jButtonConsultarColecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarColecaoMouseClicked
        TConsultarColecao tela = new TConsultarColecao(usuario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonConsultarColecaoMouseClicked

    private void jButtonRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoverMouseClicked
        TRemoverColecao tela = new TRemoverColecao(usuario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRemoverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TUsuario(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButtonCadastrarColecao;
    private javax.swing.JButton jButtonCadastrarManga;
    private javax.swing.JButton jButtonConsultarColecao;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabelColecoes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDadosUsuario;
    private javax.swing.JMenu jMenuEditarUsuario;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuRemoverUsuario;
    // End of variables declaration//GEN-END:variables
}
